server:
  port: 8080

spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=UTC
    username: root
    password: qwer1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
#-1表示没有限制
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xw.miaosha.demo.model
